name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo service docker start
          sudo docker info

      - name: Pull openjdk
        run: docker pull openjdk

      - name: Pull maven
        run: docker pull maven:3.9.2-eclipse-temurin-20

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag flower_store

      - name: Run container
        run: docker run --name flower_store_container -e POSTGRES_PASSWORD=postgres -d -p 5432:5432 flower_store
