name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest
  

    steps:
    - uses: actions/checkout@v3
      with:
          java-version: 20
          distribution: temurin
          cache: maven
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flower_store
    - name: Run container
      run: docker run --name flower_store_container:$(date +%s) -e POSTGRES_PASSWORD=postgres -d -p 5432:5432 flower_store
    
